#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MP5A3

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_GenericRifle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MP5A3.BP_MP5A3_C
// 0x0010 (0x09B0 - 0x09A0)
class ABP_MP5A3_C : public ABP_GenericRifle_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MP5A3_C;                         // 0x09A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         Adjustable_Sight_Item_Pos;                         // 0x09A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MP5A3(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MP5A3_C">();
	}
	static class ABP_MP5A3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MP5A3_C>();
	}
};
static_assert(alignof(ABP_MP5A3_C) == 0x000010, "Wrong alignment on ABP_MP5A3_C");
static_assert(sizeof(ABP_MP5A3_C) == 0x0009B0, "Wrong size on ABP_MP5A3_C");
static_assert(offsetof(ABP_MP5A3_C, UberGraphFrame_BP_MP5A3_C) == 0x0009A0, "Member 'ABP_MP5A3_C::UberGraphFrame_BP_MP5A3_C' has a wrong offset!");
static_assert(offsetof(ABP_MP5A3_C, Adjustable_Sight_Item_Pos) == 0x0009A8, "Member 'ABP_MP5A3_C::Adjustable_Sight_Item_Pos' has a wrong offset!");

}

