#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MP5A3_StaticInfo_Ironsight

#include "Basic.hpp"

#include "BP_MP5A3_StaticInfo_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MP5A3_StaticInfo_Ironsight.BP_MP5A3_StaticInfo_Ironsight_C
// 0x0000 (0x0D88 - 0x0D88)
class UBP_MP5A3_StaticInfo_Ironsight_C final : public UBP_MP5A3_StaticInfo_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MP5A3_StaticInfo_Ironsight_C">();
	}
	static class UBP_MP5A3_StaticInfo_Ironsight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MP5A3_StaticInfo_Ironsight_C>();
	}
};
static_assert(alignof(UBP_MP5A3_StaticInfo_Ironsight_C) == 0x000008, "Wrong alignment on UBP_MP5A3_StaticInfo_Ironsight_C");
static_assert(sizeof(UBP_MP5A3_StaticInfo_Ironsight_C) == 0x000D88, "Wrong size on UBP_MP5A3_StaticInfo_Ironsight_C");

}

