#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuGameMode

#include "Basic.hpp"

#include "Squad_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MenuGameMode.BP_MenuGameMode_C
// 0x0008 (0x0320 - 0x0318)
class ABP_MenuGameMode_C final : public ASQGameMode_Menu
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MenuGameMode_C">();
	}
	static class ABP_MenuGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MenuGameMode_C>();
	}
};
static_assert(alignof(ABP_MenuGameMode_C) == 0x000008, "Wrong alignment on ABP_MenuGameMode_C");
static_assert(sizeof(ABP_MenuGameMode_C) == 0x000320, "Wrong size on ABP_MenuGameMode_C");
static_assert(offsetof(ABP_MenuGameMode_C, DefaultSceneRoot) == 0x000318, "Member 'ABP_MenuGameMode_C::DefaultSceneRoot' has a wrong offset!");

}

