#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_M4_SimonOffense_Parent

#include "Basic.hpp"

#include "BP_M4A1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_M4_SimonOffense_Parent.BP_M4_SimonOffense_Parent_C
// 0x0000 (0x09A0 - 0x09A0)
class ABP_M4_SimonOffense_Parent_C : public ABP_M4A1_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_M4_SimonOffense_Parent_C">();
	}
	static class ABP_M4_SimonOffense_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_M4_SimonOffense_Parent_C>();
	}
};
static_assert(alignof(ABP_M4_SimonOffense_Parent_C) == 0x000010, "Wrong alignment on ABP_M4_SimonOffense_Parent_C");
static_assert(sizeof(ABP_M4_SimonOffense_Parent_C) == 0x0009A0, "Wrong size on ABP_M4_SimonOffense_Parent_C");

}

