#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_M14

#include "Basic.hpp"

#include "BP_GenericRifle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_M14.BP_M14_C
// 0x0000 (0x09A0 - 0x09A0)
class ABP_M14_C : public ABP_GenericRifle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_M14_C">();
	}
	static class ABP_M14_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_M14_C>();
	}
};
static_assert(alignof(ABP_M14_C) == 0x000010, "Wrong alignment on ABP_M14_C");
static_assert(sizeof(ABP_M14_C) == 0x0009A0, "Wrong size on ABP_M14_C");

}

