#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MP5A3_9mags

#include "Basic.hpp"

#include "BP_MP5A3_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MP5A3_9mags.BP_MP5A3_9mags_C
// 0x0000 (0x09B0 - 0x09B0)
class ABP_MP5A3_9mags_C final : public ABP_MP5A3_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MP5A3_9mags_C">();
	}
	static class ABP_MP5A3_9mags_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MP5A3_9mags_C>();
	}
};
static_assert(alignof(ABP_MP5A3_9mags_C) == 0x000010, "Wrong alignment on ABP_MP5A3_9mags_C");
static_assert(sizeof(ABP_MP5A3_9mags_C) == 0x0009B0, "Wrong size on ABP_MP5A3_9mags_C");

}

