#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VehicleAmmoIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_GenericWorldIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VehicleAmmoIcon.BP_VehicleAmmoIcon_C
// 0x0008 (0x0288 - 0x0280)
class ABP_VehicleAmmoIcon_C final : public ABP_GenericWorldIcon_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_VehicleAmmoIcon_C;               // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_VehicleAmmoIcon(int32 EntryPoint);
	void ChangeIconActive(bool Selected);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VehicleAmmoIcon_C">();
	}
	static class ABP_VehicleAmmoIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VehicleAmmoIcon_C>();
	}
};
static_assert(alignof(ABP_VehicleAmmoIcon_C) == 0x000008, "Wrong alignment on ABP_VehicleAmmoIcon_C");
static_assert(sizeof(ABP_VehicleAmmoIcon_C) == 0x000288, "Wrong size on ABP_VehicleAmmoIcon_C");
static_assert(offsetof(ABP_VehicleAmmoIcon_C, UberGraphFrame_BP_VehicleAmmoIcon_C) == 0x000280, "Member 'ABP_VehicleAmmoIcon_C::UberGraphFrame_BP_VehicleAmmoIcon_C' has a wrong offset!");

}

