#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EntryMap

#include "Basic.hpp"


namespace SDK::Params
{

// Function EntryMap.Kamdesh_Highlands_C.ExecuteUbergraph_EntryMap
// 0x0004 (0x0004 - 0x0000)
struct Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap) == 0x000004, "Wrong alignment on Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap");
static_assert(sizeof(Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap) == 0x000004, "Wrong size on Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap");
static_assert(offsetof(Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap, EntryPoint) == 0x000000, "Member 'Kamdesh_Highlands_C_ExecuteUbergraph_EntryMap::EntryPoint' has a wrong offset!");

}

