#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LL_WPMC_Night

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LL_WPMC_Night.LL_WPMC_Night_C
// 0x0000 (0x0230 - 0x0230)
class ALL_WPMC_Night_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LL_WPMC_Night_C">();
	}
	static class ALL_WPMC_Night_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALL_WPMC_Night_C>();
	}
};
static_assert(alignof(ALL_WPMC_Night_C) == 0x000008, "Wrong alignment on ALL_WPMC_Night_C");
static_assert(sizeof(ALL_WPMC_Night_C) == 0x000230, "Wrong size on ALL_WPMC_Night_C");

}

