#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsItem_TickBox

#include "Basic.hpp"

#include "SettingsItem_TickBox_classes.hpp"
#include "SettingsItem_TickBox_parameters.hpp"


namespace SDK
{

// Function SettingsItem_TickBox.SettingsItem_TickBox_C.OnClicked__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class USettingsItem_TickBox_C*          Button_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USettingsItem_TickBox_C::OnClicked__DelegateSignature(bool bSelected_0, class USettingsItem_TickBox_C* Button_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "OnClicked__DelegateSignature");

	Params::SettingsItem_TickBox_C_OnClicked__DelegateSignature Parms{};

	Parms.bSelected_0 = bSelected_0;
	Parms.Button_0 = Button_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.OnHover__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bHovered_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USettingsItem_TickBox_C::OnHover__DelegateSignature(bool bHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "OnHover__DelegateSignature");

	Params::SettingsItem_TickBox_C_OnHover__DelegateSignature Parms{};

	Parms.bHovered_0 = bHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.ExecuteUbergraph_SettingsItem_TickBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USettingsItem_TickBox_C::ExecuteUbergraph_SettingsItem_TickBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "ExecuteUbergraph_SettingsItem_TickBox");

	Params::SettingsItem_TickBox_C_ExecuteUbergraph_SettingsItem_TickBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.SetSettingValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Setting_Name                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void USettingsItem_TickBox_C::SetSettingValue(class FName Setting_Name, const class FString& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "SetSettingValue");

	Params::SettingsItem_TickBox_C_SetSettingValue Parms{};

	Parms.Setting_Name = Setting_Name;
	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USettingsItem_TickBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettingsItem_TickBox_C::BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USettingsItem_TickBox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "PreConstruct");

	Params::SettingsItem_TickBox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.SetSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USettingsItem_TickBox_C::SetSelected(bool bSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "SetSelected");

	Params::SettingsItem_TickBox_C_SetSelected Parms{};

	Parms.bSelected_0 = bSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.UpdateColors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USettingsItem_TickBox_C::UpdateColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "UpdateColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.SetText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void USettingsItem_TickBox_C::SetText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "SetText");

	Params::SettingsItem_TickBox_C_SetText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.Bind_LineColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor USettingsItem_TickBox_C::Bind_LineColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "Bind_LineColor");

	Params::SettingsItem_TickBox_C_Bind_LineColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.Bind_TextColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor USettingsItem_TickBox_C::Bind_TextColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "Bind_TextColor");

	Params::SettingsItem_TickBox_C_Bind_TextColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.Update Tick Box
// (Public, BlueprintCallable, BlueprintEvent)

void USettingsItem_TickBox_C::Update_Tick_Box()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "Update Tick Box");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.GetValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString USettingsItem_TickBox_C::GetValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "GetValue");

	Params::SettingsItem_TickBox_C_GetValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SettingsItem_TickBox.SettingsItem_TickBox_C.SetBoxWidth
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InWidth                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USettingsItem_TickBox_C::SetBoxWidth(float InWidth)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsItem_TickBox_C", "SetBoxWidth");

	Params::SettingsItem_TickBox_C_SetBoxWidth Parms{};

	Parms.InWidth = InWidth;

	UObject::ProcessEvent(Func, &Parms);
}

}

