#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TimelinePoint

#include "Basic.hpp"

#include "UMG_TimelinePoint_classes.hpp"
#include "UMG_TimelinePoint_parameters.hpp"


namespace SDK
{

// Function UMG_TimelinePoint.UMG_TimelinePoint_C.ExecuteUbergraph_UMG_TimelinePoint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelinePoint_C::ExecuteUbergraph_UMG_TimelinePoint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelinePoint_C", "ExecuteUbergraph_UMG_TimelinePoint");

	Params::UMG_TimelinePoint_C_ExecuteUbergraph_UMG_TimelinePoint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelinePoint.UMG_TimelinePoint_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_TimelinePoint_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelinePoint_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_TimelinePoint.UMG_TimelinePoint_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_TimelinePoint_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelinePoint_C", "PreConstruct");

	Params::UMG_TimelinePoint_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelinePoint.UMG_TimelinePoint_C.SetMarked
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewMarked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_TimelinePoint_C::SetMarked(bool bNewMarked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelinePoint_C", "SetMarked");

	Params::UMG_TimelinePoint_C_SetMarked Parms{};

	Parms.bNewMarked = bNewMarked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelinePoint.UMG_TimelinePoint_C.ChangeColor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLinearColor                     NewColor                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelinePoint_C::ChangeColor(const struct FLinearColor& NewColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelinePoint_C", "ChangeColor");

	Params::UMG_TimelinePoint_C_ChangeColor Parms{};

	Parms.NewColor = std::move(NewColor);

	UObject::ProcessEvent(Func, &Parms);
}

}

