#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TimelineHorizontalLine

#include "Basic.hpp"

#include "UMG_TimelineHorizontalLine_classes.hpp"
#include "UMG_TimelineHorizontalLine_parameters.hpp"


namespace SDK
{

// Function UMG_TimelineHorizontalLine.UMG_TimelineHorizontalLine_C.ExecuteUbergraph_UMG_TimelineHorizontalLine
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineHorizontalLine_C::ExecuteUbergraph_UMG_TimelineHorizontalLine(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineHorizontalLine_C", "ExecuteUbergraph_UMG_TimelineHorizontalLine");

	Params::UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineHorizontalLine.UMG_TimelineHorizontalLine_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_TimelineHorizontalLine_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineHorizontalLine_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

