#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_CategoryIcon

#include "Basic.hpp"

#include "UMG_CategoryIcon_classes.hpp"
#include "UMG_CategoryIcon_parameters.hpp"


namespace SDK
{

// Function UMG_CategoryIcon.UMG_CategoryIcon_C.ExecuteUbergraph_UMG_CategoryIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_CategoryIcon_C::ExecuteUbergraph_UMG_CategoryIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "ExecuteUbergraph_UMG_CategoryIcon");

	Params::UMG_CategoryIcon_C_ExecuteUbergraph_UMG_CategoryIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_CategoryIcon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_CategoryIcon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "PreConstruct");

	Params::UMG_CategoryIcon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.GetToolTipWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUMG_CategoryIcon_C::GetToolTipWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "GetToolTipWidget");

	Params::UMG_CategoryIcon_C_GetToolTipWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.GetValueTextWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTextBlock*                       ScoreValue_0                                           (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_CategoryIcon_C::GetValueTextWidget(class UTextBlock** ScoreValue_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "GetValueTextWidget");

	Params::UMG_CategoryIcon_C_GetValueTextWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ScoreValue_0 != nullptr)
		*ScoreValue_0 = Parms.ScoreValue_0;
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.SetScoreValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UUMG_CategoryIcon_C::SetScoreValue(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "SetScoreValue");

	Params::UMG_CategoryIcon_C_SetScoreValue Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.SwitchToValueMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ValueMode                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_CategoryIcon_C::SwitchToValueMode(bool ValueMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "SwitchToValueMode");

	Params::UMG_CategoryIcon_C_SwitchToValueMode Parms{};

	Parms.ValueMode = ValueMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.ShowBackground
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_CategoryIcon_C::ShowBackground(bool NewShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "ShowBackground");

	Params::UMG_CategoryIcon_C_ShowBackground Parms{};

	Parms.NewShow = NewShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_CategoryIcon.UMG_CategoryIcon_C.SetNewWidth
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Width                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_CategoryIcon_C::SetNewWidth(float& Width)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_CategoryIcon_C", "SetNewWidth");

	Params::UMG_CategoryIcon_C_SetNewWidth Parms{};

	Parms.Width = Width;

	UObject::ProcessEvent(Func, &Parms);

	Width = Parms.Width;
}

}

