#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_FactionVoteDetails

#include "Basic.hpp"

#include "UMG_FactionVoteDetails_classes.hpp"
#include "UMG_FactionVoteDetails_parameters.hpp"


namespace SDK
{

// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.CloseWindow__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UUMG_FactionVoteDetails_C::CloseWindow__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "CloseWindow__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.ExecuteUbergraph_UMG_FactionVoteDetails
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_FactionVoteDetails_C::ExecuteUbergraph_UMG_FactionVoteDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "ExecuteUbergraph_UMG_FactionVoteDetails");

	Params::UMG_FactionVoteDetails_C_ExecuteUbergraph_UMG_FactionVoteDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.BndEvt__UMG_FactionVoteDetails_UI_VoteButton_K2Node_ComponentBoundEvent_3_VoteSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FName                             VoteId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_FactionVoteDetails_C::BndEvt__UMG_FactionVoteDetails_UI_VoteButton_K2Node_ComponentBoundEvent_3_VoteSelected__DelegateSignature(class FName VoteId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "BndEvt__UMG_FactionVoteDetails_UI_VoteButton_K2Node_ComponentBoundEvent_3_VoteSelected__DelegateSignature");

	Params::UMG_FactionVoteDetails_C_BndEvt__UMG_FactionVoteDetails_UI_VoteButton_K2Node_ComponentBoundEvent_3_VoteSelected__DelegateSignature Parms{};

	Parms.VoteId = VoteId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.BndEvt__UMG_LayerVoteDetails_PrevButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUMG_FactionVoteDetails_C::BndEvt__UMG_LayerVoteDetails_PrevButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "BndEvt__UMG_LayerVoteDetails_PrevButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.BndEvt__UMG_LayerVoteDetails_NextButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUMG_FactionVoteDetails_C::BndEvt__UMG_LayerVoteDetails_NextButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "BndEvt__UMG_LayerVoteDetails_NextButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.BndEvt__UMG_LayerVoteDetails_CloseButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUMG_FactionVoteDetails_C::BndEvt__UMG_LayerVoteDetails_CloseButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "BndEvt__UMG_LayerVoteDetails_CloseButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_FactionVoteDetails_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "Tick");

	Params::UMG_FactionVoteDetails_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_FactionVoteDetails_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.FillFromFaction
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USQFactionSetup*                  Faction                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USQVoteSessionClient*             Session                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             FactionID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USQLayer*                         Layer                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TeamId_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    SingleMode_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    EnemyTeam                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_FactionVoteDetails_C::FillFromFaction(class USQFactionSetup* Faction, class USQVoteSessionClient* Session, class FName FactionID, class USQLayer* Layer, int32 TeamId_0, bool SingleMode_0, bool EnemyTeam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "FillFromFaction");

	Params::UMG_FactionVoteDetails_C_FillFromFaction Parms{};

	Parms.Faction = Faction;
	Parms.Session = Session;
	Parms.FactionID = FactionID;
	Parms.Layer = Layer;
	Parms.TeamId_0 = TeamId_0;
	Parms.SingleMode_0 = SingleMode_0;
	Parms.EnemyTeam = EnemyTeam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.GetChoiceIndex
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ChoiceId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_FactionVoteDetails_C::GetChoiceIndex(class FName ChoiceId, int32* Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "GetChoiceIndex");

	Params::UMG_FactionVoteDetails_C_GetChoiceIndex Parms{};

	Parms.ChoiceId = ChoiceId;

	UObject::ProcessEvent(Func, &Parms);

	if (Index_0 != nullptr)
		*Index_0 = Parms.Index_0;
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.UpdateNavigationArrows
// (Public, BlueprintCallable, BlueprintEvent)

void UUMG_FactionVoteDetails_C::UpdateNavigationArrows()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "UpdateNavigationArrows");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.GetFactionSetup
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USQFactionSetup*                  Faction                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             FactionID                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_FactionVoteDetails_C::GetFactionSetup(int32 Index_0, class USQFactionSetup** Faction, class FName* FactionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "GetFactionSetup");

	Params::UMG_FactionVoteDetails_C_GetFactionSetup Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Faction != nullptr)
		*Faction = Parms.Faction;

	if (FactionID != nullptr)
		*FactionID = Parms.FactionID;
}


// Function UMG_FactionVoteDetails.UMG_FactionVoteDetails_C.UpdateUnitTypeIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UUMG_FactionVoteDetails_C::UpdateUnitTypeIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_FactionVoteDetails_C", "UpdateUnitTypeIcon");

	UObject::ProcessEvent(Func, nullptr);
}

}

