#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TimelineTooltipElement

#include "Basic.hpp"

#include "UMG_TimelineTooltipElement_classes.hpp"
#include "UMG_TimelineTooltipElement_parameters.hpp"


namespace SDK
{

// Function UMG_TimelineTooltipElement.UMG_TimelineTooltipElement_C.ExecuteUbergraph_UMG_TimelineTooltipElement
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipElement_C::ExecuteUbergraph_UMG_TimelineTooltipElement(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipElement_C", "ExecuteUbergraph_UMG_TimelineTooltipElement");

	Params::UMG_TimelineTooltipElement_C_ExecuteUbergraph_UMG_TimelineTooltipElement Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipElement.UMG_TimelineTooltipElement_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_TimelineTooltipElement_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipElement_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_TimelineTooltipElement.UMG_TimelineTooltipElement_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewText                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Tickets                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipElement_C::Update(const class FText& NewText, int32 Tickets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipElement_C", "Update");

	Params::UMG_TimelineTooltipElement_C_Update Parms{};

	Parms.NewText = std::move(NewText);
	Parms.Tickets = Tickets;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipElement.UMG_TimelineTooltipElement_C.ChangeColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLinearColor                     NewColor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipElement_C::ChangeColor(const struct FLinearColor& NewColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipElement_C", "ChangeColor");

	Params::UMG_TimelineTooltipElement_C_ChangeColor Parms{};

	Parms.NewColor = std::move(NewColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipElement.UMG_TimelineTooltipElement_C.ChangeTextValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UUMG_TimelineTooltipElement_C::ChangeTextValue(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipElement_C", "ChangeTextValue");

	Params::UMG_TimelineTooltipElement_C_ChangeTextValue Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}

}

