#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_ScoreboardPlayer

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "FSQRoleEntry_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.ExecuteUbergraph_UMG_ScoreboardPlayer
// 0x0110 (0x0110 - 0x0000)
struct UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UTexture2D*                             Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_1;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_2;                            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        K2Node_MakeArray_Array;                            // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASQPlayerController*                    K2Node_DynamicCast_AsSQPlayer_Controller;          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Same_Squad_ReturnValue;                   // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFireTeamLeader_ReturnValue;             // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_53[0x5];                                       // 0x0053(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Leader_Text_ReturnValue;                  // 0x0058(0x0018)()
	bool                                          CallFunc_IsSquadLeader_ReturnValue;                // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_72[0x6];                                       // 0x0072(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default;                             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default_2;                           // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_FT_Color_ReturnValue;                     // 0x0090(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x00A8(0x0028)()
	struct FLinearColor                           CallFunc_FT_Color_ReturnValue_1;                   // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x00E8(0x0028)()
};
static_assert(alignof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer");
static_assert(sizeof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer) == 0x000110, "Wrong size on UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, EntryPoint) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::EntryPoint' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_bool_Variable) == 0x000004, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_byte_Variable) == 0x000005, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_byte_Variable_1) == 0x000006, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_bool_Variable_1) == 0x000007, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_object_Variable) == 0x000008, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_bool_Variable_2) == 0x000010, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_object_Variable_1) == 0x000018, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_object_Variable_2) == 0x000020, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_bool_Variable_3) == 0x000028, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_byte_Variable_2) == 0x000029, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, Temp_byte_Variable_3) == 0x00002A, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_MakeArray_Array) == 0x000030, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_GetOwningPlayer_ReturnValue) == 0x000040, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_DynamicCast_AsSQPlayer_Controller) == 0x000048, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_DynamicCast_AsSQPlayer_Controller' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_Same_Squad_ReturnValue) == 0x000051, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_Same_Squad_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_IsFireTeamLeader_ReturnValue) == 0x000052, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_IsFireTeamLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_Leader_Text_ReturnValue) == 0x000058, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_Leader_Text_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_IsSquadLeader_ReturnValue) == 0x000070, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_IsSquadLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_BooleanOR_ReturnValue) == 0x000071, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_Select_Default) == 0x000078, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_Select_Default_1) == 0x000080, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_Select_Default_2) == 0x000088, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_FT_Color_ReturnValue) == 0x000090, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_FT_Color_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_Select_Default_3) == 0x0000A0, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_MakeStruct_SlateColor) == 0x0000A8, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, CallFunc_FT_Color_ReturnValue_1) == 0x0000D0, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::CallFunc_FT_Color_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_Event_IsDesignTime) == 0x0000E0, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer, K2Node_MakeStruct_SlateColor_1) == 0x0000E8, "Member 'UMG_ScoreboardPlayer_C_ExecuteUbergraph_UMG_ScoreboardPlayer::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UMG_ScoreboardPlayer_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_PreConstruct) == 0x000001, "Wrong alignment on UMG_ScoreboardPlayer_C_PreConstruct");
static_assert(sizeof(UMG_ScoreboardPlayer_C_PreConstruct) == 0x000001, "Wrong size on UMG_ScoreboardPlayer_C_PreConstruct");
static_assert(offsetof(UMG_ScoreboardPlayer_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.Same Squad
// 0x0004 (0x0004 - 0x0000)
struct UMG_ScoreboardPlayer_C_Same_Squad final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_Same_Squad) == 0x000001, "Wrong alignment on UMG_ScoreboardPlayer_C_Same_Squad");
static_assert(sizeof(UMG_ScoreboardPlayer_C_Same_Squad) == 0x000004, "Wrong size on UMG_ScoreboardPlayer_C_Same_Squad");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Same_Squad, ReturnValue) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_Same_Squad::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Same_Squad, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'UMG_ScoreboardPlayer_C_Same_Squad::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Same_Squad, CallFunc_IsValid_ReturnValue_1) == 0x000002, "Member 'UMG_ScoreboardPlayer_C_Same_Squad::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Same_Squad, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000003, "Member 'UMG_ScoreboardPlayer_C_Same_Squad::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.Leader Text
// 0x00A8 (0x00A8 - 0x0000)
struct UMG_ScoreboardPlayer_C_Leader_Text final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0020(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0038(0x0018)()
	bool                                          Temp_bool_Variable_1;                              // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFireTeamLeader_ReturnValue;             // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0058(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0070(0x0018)()
	bool                                          CallFunc_IsSquadLeader_ReturnValue;                // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_1;                           // 0x0090(0x0018)()
};
static_assert(alignof(UMG_ScoreboardPlayer_C_Leader_Text) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_Leader_Text");
static_assert(sizeof(UMG_ScoreboardPlayer_C_Leader_Text) == 0x0000A8, "Wrong size on UMG_ScoreboardPlayer_C_Leader_Text");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, ReturnValue) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, Temp_bool_Variable) == 0x000018, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, Temp_text_Variable) == 0x000020, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, Temp_text_Variable_1) == 0x000038, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, Temp_bool_Variable_1) == 0x000050, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, CallFunc_IsFireTeamLeader_ReturnValue) == 0x000051, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::CallFunc_IsFireTeamLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, CallFunc_GetText_ReturnValue) == 0x000058, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, K2Node_Select_Default) == 0x000070, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, CallFunc_IsSquadLeader_ReturnValue) == 0x000088, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::CallFunc_IsSquadLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Leader_Text, K2Node_Select_Default_1) == 0x000090, "Member 'UMG_ScoreboardPlayer_C_Leader_Text::K2Node_Select_Default_1' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.FT Color
// 0x0038 (0x0038 - 0x0000)
struct UMG_ScoreboardPlayer_C_FT_Color final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFireTeamIndex_ReturnValue;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFireTeamIndex_ReturnValue_1;           // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQColorsDataAsset*                     CallFunc_Get_SQHUD_Colors_ColorsDataAsset;         // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColor_ReturnValue;                     // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_FT_Color) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_FT_Color");
static_assert(sizeof(UMG_ScoreboardPlayer_C_FT_Color) == 0x000038, "Wrong size on UMG_ScoreboardPlayer_C_FT_Color");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, ReturnValue) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_FT_Color::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, CallFunc_GetFireTeamIndex_ReturnValue) == 0x000010, "Member 'UMG_ScoreboardPlayer_C_FT_Color::CallFunc_GetFireTeamIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, CallFunc_GetFireTeamIndex_ReturnValue_1) == 0x000014, "Member 'UMG_ScoreboardPlayer_C_FT_Color::CallFunc_GetFireTeamIndex_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000018, "Member 'UMG_ScoreboardPlayer_C_FT_Color::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, CallFunc_Get_SQHUD_Colors_ColorsDataAsset) == 0x000020, "Member 'UMG_ScoreboardPlayer_C_FT_Color::CallFunc_Get_SQHUD_Colors_ColorsDataAsset' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_FT_Color, CallFunc_GetColor_ReturnValue) == 0x000028, "Member 'UMG_ScoreboardPlayer_C_FT_Color::CallFunc_GetColor_ReturnValue' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.Get Position
// 0x0008 (0x0008 - 0x0000)
struct UMG_ScoreboardPlayer_C_Get_Position final
{
public:
	class ASQSquadState*                          L_Squad;                                           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_Get_Position) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_Get_Position");
static_assert(sizeof(UMG_ScoreboardPlayer_C_Get_Position) == 0x000008, "Wrong size on UMG_ScoreboardPlayer_C_Get_Position");
static_assert(offsetof(UMG_ScoreboardPlayer_C_Get_Position, L_Squad) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_Get_Position::L_Squad' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.GetRoleIcon
// 0x0120 (0x0120 - 0x0000)
struct UMG_ScoreboardPlayer_C_GetRoleIcon final
{
public:
	class UTexture2D*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQRoleSettings*                        CallFunc_GetCurrentRole_ReturnValue;               // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAlive_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USQRoleSettings*                        CallFunc_GetDeployRole_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        K2Node_Select_Default;                             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_SQRoleSettings_C*                   K2Node_DynamicCast_AsBP_SQRole_Settings;           // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRoleEntry_Success;                     // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFSQRoleEntry                          CallFunc_GetRoleEntry_RoleEntry;                   // 0x0040(0x00C0)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue; // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_GetRoleIcon) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_GetRoleIcon");
static_assert(sizeof(UMG_ScoreboardPlayer_C_GetRoleIcon) == 0x000120, "Wrong size on UMG_ScoreboardPlayer_C_GetRoleIcon");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, ReturnValue) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, Temp_bool_Variable) == 0x000008, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_GetCurrentRole_ReturnValue) == 0x000010, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_GetCurrentRole_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_IsAlive_ReturnValue) == 0x000019, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_IsAlive_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_GetDeployRole_ReturnValue) == 0x000020, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_GetDeployRole_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, K2Node_Select_Default) == 0x000028, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, K2Node_DynamicCast_AsBP_SQRole_Settings) == 0x000030, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::K2Node_DynamicCast_AsBP_SQRole_Settings' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_IsValid_ReturnValue_1) == 0x000039, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_GetRoleEntry_Success) == 0x00003A, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_GetRoleEntry_Success' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_GetRoleEntry_RoleEntry) == 0x000040, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_GetRoleEntry_RoleEntry' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x000100, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue) == 0x000108, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, K2Node_DynamicCast_AsTexture_2D) == 0x000110, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_GetRoleIcon, K2Node_DynamicCast_bSuccess_1) == 0x000118, "Member 'UMG_ScoreboardPlayer_C_GetRoleIcon::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.UpdateStatSpace
// 0x0040 (0x0040 - 0x0000)
struct UMG_ScoreboardPlayer_C_UpdateStatSpace final
{
public:
	TArray<class USizeBox*>                       SizeBoxList;                                       // 0x0000(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USizeBox*                               CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USizeBox*>                       K2Node_MakeArray_Array;                            // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_UpdateStatSpace) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_UpdateStatSpace");
static_assert(sizeof(UMG_ScoreboardPlayer_C_UpdateStatSpace) == 0x000040, "Wrong size on UMG_ScoreboardPlayer_C_UpdateStatSpace");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, SizeBoxList) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::SizeBoxList' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, CallFunc_Array_Get_Item) == 0x000020, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, CallFunc_Less_IntInt_ReturnValue) == 0x00002C, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_UpdateStatSpace, K2Node_MakeArray_Array) == 0x000030, "Member 'UMG_ScoreboardPlayer_C_UpdateStatSpace::K2Node_MakeArray_Array' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.ShowHealhIconTooltip
// 0x0020 (0x0020 - 0x0000)
struct UMG_ScoreboardPlayer_C_ShowHealhIconTooltip final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetHealthTooltip_ReturnValue;             // 0x0008(0x0018)()
};
static_assert(alignof(UMG_ScoreboardPlayer_C_ShowHealhIconTooltip) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_ShowHealhIconTooltip");
static_assert(sizeof(UMG_ScoreboardPlayer_C_ShowHealhIconTooltip) == 0x000020, "Wrong size on UMG_ScoreboardPlayer_C_ShowHealhIconTooltip");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ShowHealhIconTooltip, ReturnValue) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_ShowHealhIconTooltip::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_ShowHealhIconTooltip, CallFunc_GetHealthTooltip_ReturnValue) == 0x000008, "Member 'UMG_ScoreboardPlayer_C_ShowHealhIconTooltip::CallFunc_GetHealthTooltip_ReturnValue' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.SetTooltipWidget
// 0x0008 (0x0008 - 0x0000)
struct UMG_ScoreboardPlayer_C_SetTooltipWidget final
{
public:
	class UUMG_Tooltip_C*                         InTooltip;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_SetTooltipWidget) == 0x000008, "Wrong alignment on UMG_ScoreboardPlayer_C_SetTooltipWidget");
static_assert(sizeof(UMG_ScoreboardPlayer_C_SetTooltipWidget) == 0x000008, "Wrong size on UMG_ScoreboardPlayer_C_SetTooltipWidget");
static_assert(offsetof(UMG_ScoreboardPlayer_C_SetTooltipWidget, InTooltip) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_SetTooltipWidget::InTooltip' has a wrong offset!");

// Function UMG_ScoreboardPlayer.UMG_ScoreboardPlayer_C.RescaleWidget
// 0x0014 (0x0014 - 0x0000)
struct UMG_ScoreboardPlayer_C_RescaleWidget final
{
public:
	float                                         NewIconSize;                                       // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NameWidthScaler;                                   // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue;                       // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ScoreboardPlayer_C_RescaleWidget) == 0x000004, "Wrong alignment on UMG_ScoreboardPlayer_C_RescaleWidget");
static_assert(sizeof(UMG_ScoreboardPlayer_C_RescaleWidget) == 0x000014, "Wrong size on UMG_ScoreboardPlayer_C_RescaleWidget");
static_assert(offsetof(UMG_ScoreboardPlayer_C_RescaleWidget, NewIconSize) == 0x000000, "Member 'UMG_ScoreboardPlayer_C_RescaleWidget::NewIconSize' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_RescaleWidget, NameWidthScaler) == 0x000004, "Member 'UMG_ScoreboardPlayer_C_RescaleWidget::NameWidthScaler' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_RescaleWidget, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000008, "Member 'UMG_ScoreboardPlayer_C_RescaleWidget::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_RescaleWidget, CallFunc_FClamp_ReturnValue) == 0x00000C, "Member 'UMG_ScoreboardPlayer_C_RescaleWidget::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ScoreboardPlayer_C_RescaleWidget, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000010, "Member 'UMG_ScoreboardPlayer_C_RescaleWidget::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");

}

