#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TimelineHorizontalLine

#include "Basic.hpp"


namespace SDK::Params
{

// Function UMG_TimelineHorizontalLine.UMG_TimelineHorizontalLine_C.ExecuteUbergraph_UMG_TimelineHorizontalLine
// 0x0020 (0x0020 - 0x0000)
struct UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0018)()
};
static_assert(alignof(UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine) == 0x000008, "Wrong alignment on UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine");
static_assert(sizeof(UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine) == 0x000020, "Wrong size on UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine");
static_assert(offsetof(UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine, EntryPoint) == 0x000000, "Member 'UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine::EntryPoint' has a wrong offset!");
static_assert(offsetof(UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine, CallFunc_Conv_IntToText_ReturnValue) == 0x000008, "Member 'UMG_TimelineHorizontalLine_C_ExecuteUbergraph_UMG_TimelineHorizontalLine::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

}

