#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TimelineTooltipList

#include "Basic.hpp"

#include "UMG_TimelineTooltipList_classes.hpp"
#include "UMG_TimelineTooltipList_parameters.hpp"


namespace SDK
{

// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.ExecuteUbergraph_UMG_TimelineTooltipList
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipList_C::ExecuteUbergraph_UMG_TimelineTooltipList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "ExecuteUbergraph_UMG_TimelineTooltipList");

	Params::UMG_TimelineTooltipList_C_ExecuteUbergraph_UMG_TimelineTooltipList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUMG_TimelineTooltipList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.SetTicketsValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Tickets                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipList_C::SetTicketsValue(int32 Tickets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "SetTicketsValue");

	Params::UMG_TimelineTooltipList_C_SetTicketsValue Parms{};

	Parms.Tickets = Tickets;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.ShowSeparator
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_TimelineTooltipList_C::ShowSeparator(bool Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "ShowSeparator");

	Params::UMG_TimelineTooltipList_C_ShowSeparator Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.FillEvents
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<int32>                           Events                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class USQEndStatsComponent*             EndRoundComp                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TicketsPoint                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_TimelineTooltipList_C::FillEvents(int32& TeamId, TArray<int32>& Events, class USQEndStatsComponent*& EndRoundComp, int32& TicketsPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "FillEvents");

	Params::UMG_TimelineTooltipList_C_FillEvents Parms{};

	Parms.TeamId = TeamId;
	Parms.Events = std::move(Events);
	Parms.EndRoundComp = EndRoundComp;
	Parms.TicketsPoint = TicketsPoint;

	UObject::ProcessEvent(Func, &Parms);

	TeamId = Parms.TeamId;
	Events = std::move(Parms.Events);
	EndRoundComp = Parms.EndRoundComp;
	TicketsPoint = Parms.TicketsPoint;
}


// Function UMG_TimelineTooltipList.UMG_TimelineTooltipList_C.GetElementText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESQTicketChangeReason                   ChangeReason                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USQVehicleSettings*               Vehicle                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             NewText                                                (Parm, OutParm)

void UUMG_TimelineTooltipList_C::GetElementText(ESQTicketChangeReason ChangeReason, class USQVehicleSettings* Vehicle, class FText* NewText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_TimelineTooltipList_C", "GetElementText");

	Params::UMG_TimelineTooltipList_C_GetElementText Parms{};

	Parms.ChangeReason = ChangeReason;
	Parms.Vehicle = Vehicle;

	UObject::ProcessEvent(Func, &Parms);

	if (NewText != nullptr)
		*NewText = std::move(Parms.NewText);
}

}

