#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_EndTicketDetailsScreen

#include "Basic.hpp"

#include "W_EndTicketDetailsScreen_classes.hpp"
#include "W_EndTicketDetailsScreen_parameters.hpp"


namespace SDK
{

// Function W_EndTicketDetailsScreen.W_EndTicketDetailsScreen_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndTicketDetailsScreen_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndTicketDetailsScreen_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}

}

