#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_EndRound

#include "Basic.hpp"

#include "W_EndRound_classes.hpp"
#include "W_EndRound_parameters.hpp"


namespace SDK
{

// Function W_EndRound.W_EndRound_C.ExecuteUbergraph_W_EndRound
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRound_C::ExecuteUbergraph_W_EndRound(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "ExecuteUbergraph_W_EndRound");

	Params::W_EndRound_C_ExecuteUbergraph_W_EndRound Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRound.W_EndRound_C.Event Play Team Sounds
// (BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::Event_Play_Team_Sounds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "Event Play Team Sounds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.HUD Scoreboard
// (BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::HUD_Scoreboard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "HUD Scoreboard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_EndRound_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.OnLoaded_4D00979747334CD613094AA5E0E4B4C2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRound_C::OnLoaded_4D00979747334CD613094AA5E0E4B4C2(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "OnLoaded_4D00979747334CD613094AA5E0E4B4C2");

	Params::W_EndRound_C_OnLoaded_4D00979747334CD613094AA5E0E4B4C2 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRound.W_EndRound_C.Init End Round Screen
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::Init_End_Round_Screen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "Init End Round Screen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.RefreshStatus
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::RefreshStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "RefreshStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.UpdateResults
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USQEndStatsComponent*             EndStats                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRound_C::UpdateResults(class USQEndStatsComponent* EndStats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "UpdateResults");

	Params::W_EndRound_C_UpdateResults Parms{};

	Parms.EndStats = EndStats;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRound.W_EndRound_C.SecondsToText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Seconds                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             TimeText                                               (Parm, OutParm)

void UW_EndRound_C::SecondsToText(int32 Seconds, class FText* TimeText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "SecondsToText");

	Params::W_EndRound_C_SecondsToText Parms{};

	Parms.Seconds = Seconds;

	UObject::ProcessEvent(Func, &Parms);

	if (TimeText != nullptr)
		*TimeText = std::move(Parms.TimeText);
}


// Function W_EndRound.W_EndRound_C.ApplyDrawColors
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::ApplyDrawColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "ApplyDrawColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.ApplyDefeatColors
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::ApplyDefeatColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "ApplyDefeatColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.ApplyWinColors
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::ApplyWinColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "ApplyWinColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.FillPlayerCallouts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::FillPlayerCallouts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "FillPlayerCallouts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.GetCalloutData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSQPlayerCalloutScore            PlayerCallout                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// class FText                             Title                                                  (Parm, OutParm)
// TSoftObjectPtr<class UTexture2D>        Flag                                                   (Parm, OutParm, HasGetValueTypeHash)
// class FText                             Name_0                                                 (Parm, OutParm)
// bool                                    Valid                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             Tooltip                                                (Parm, OutParm)
// class FText                             AdditionalText                                         (Parm, OutParm)

void UW_EndRound_C::GetCalloutData(struct FSQPlayerCalloutScore& PlayerCallout, class FText* Title, TSoftObjectPtr<class UTexture2D>* Flag, class FText* Name_0, bool* Valid, class FText* Tooltip, class FText* AdditionalText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "GetCalloutData");

	Params::W_EndRound_C_GetCalloutData Parms{};

	Parms.PlayerCallout = std::move(PlayerCallout);

	UObject::ProcessEvent(Func, &Parms);

	PlayerCallout = std::move(Parms.PlayerCallout);

	if (Title != nullptr)
		*Title = std::move(Parms.Title);

	if (Flag != nullptr)
		*Flag = Parms.Flag;

	if (Name_0 != nullptr)
		*Name_0 = std::move(Parms.Name_0);

	if (Valid != nullptr)
		*Valid = Parms.Valid;

	if (Tooltip != nullptr)
		*Tooltip = std::move(Parms.Tooltip);

	if (AdditionalText != nullptr)
		*AdditionalText = std::move(Parms.AdditionalText);
}


// Function W_EndRound.W_EndRound_C.UpdateTicketsIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::UpdateTicketsIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "UpdateTicketsIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRound.W_EndRound_C.UpdateTeamTicketsCount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_EndRound_C::UpdateTeamTicketsCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRound_C", "UpdateTeamTicketsCount");

	UObject::ProcessEvent(Func, nullptr);
}

}

