#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_EndRoundMainScreen

#include "Basic.hpp"

#include "W_EndRoundMainScreen_classes.hpp"
#include "W_EndRoundMainScreen_parameters.hpp"


namespace SDK
{

// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ExecuteUbergraph_W_EndRoundMainScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ExecuteUbergraph_W_EndRoundMainScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ExecuteUbergraph_W_EndRoundMainScreen");

	Params::W_EndRoundMainScreen_C_ExecuteUbergraph_W_EndRoundMainScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.BndEvt__W_EndRoundMainScreen_TimelineButton_K2Node_ComponentBoundEvent_3_OnHover__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bHovered                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_EndRoundMainScreen_C::BndEvt__W_EndRoundMainScreen_TimelineButton_K2Node_ComponentBoundEvent_3_OnHover__DelegateSignature(bool bHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "BndEvt__W_EndRoundMainScreen_TimelineButton_K2Node_ComponentBoundEvent_3_OnHover__DelegateSignature");

	Params::W_EndRoundMainScreen_C_BndEvt__W_EndRoundMainScreen_TimelineButton_K2Node_ComponentBoundEvent_3_OnHover__DelegateSignature Parms{};

	Parms.bHovered = bHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	Params::W_EndRoundMainScreen_C_BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_1_OnHover__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bHovered                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_EndRoundMainScreen_C::BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_1_OnHover__DelegateSignature(bool bHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_1_OnHover__DelegateSignature");

	Params::W_EndRoundMainScreen_C_BndEvt__W_EndRoundMainScreen_DetailsButton_K2Node_ComponentBoundEvent_1_OnHover__DelegateSignature Parms{};

	Parms.bHovered = bHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_EndRoundMainScreen_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.SwitchToScreen
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          NewWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::SwitchToScreen(class UWidget* NewWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "SwitchToScreen");

	Params::W_EndRoundMainScreen_C_SwitchToScreen Parms{};

	Parms.NewWidget = NewWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.BndEvt__W_EndRoundMainScreen_MuteButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::BndEvt__W_EndRoundMainScreen_MuteButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "BndEvt__W_EndRoundMainScreen_MuteButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	Params::W_EndRoundMainScreen_C_BndEvt__W_EndRoundMainScreen_MuteButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_EndRoundMainScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.Finished_7AFC90304EB7F26E14DF33924515A5C7
// (BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::Finished_7AFC90304EB7F26E14DF33924515A5C7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "Finished_7AFC90304EB7F26E14DF33924515A5C7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.MakeScreenActive
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::MakeScreenActive(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "MakeScreenActive");

	Params::W_EndRoundMainScreen_C_MakeScreenActive Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.CustomTickFunction
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::CustomTickFunction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "CustomTickFunction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.IsVotingEnabled
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_EndRoundMainScreen_C::IsVotingEnabled(bool* Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "IsVotingEnabled");

	Params::W_EndRoundMainScreen_C_IsVotingEnabled Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Enabled != nullptr)
		*Enabled = Parms.Enabled;
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowVotingScreen
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::ShowVotingScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowVotingScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.InsertVoteWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      VoteWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CanVote                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_EndRoundMainScreen_C::InsertVoteWidget(class UUserWidget* VoteWidget, bool CanVote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "InsertVoteWidget");

	Params::W_EndRoundMainScreen_C_InsertVoteWidget Parms{};

	Parms.VoteWidget = VoteWidget;
	Parms.CanVote = CanVote;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.VoteEnded
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::VoteEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "VoteEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.UpdateSquadChatButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Selected                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_EndRoundMainScreen_C::UpdateSquadChatButton(bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "UpdateSquadChatButton");

	Params::W_EndRoundMainScreen_C_UpdateSquadChatButton Parms{};

	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.BindButtons
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::BindButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "BindButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowSummary
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ShowSummary(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowSummary");

	Params::W_EndRoundMainScreen_C_ShowSummary Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowScoreboard
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ShowScoreboard(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowScoreboard");

	Params::W_EndRoundMainScreen_C_ShowScoreboard Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowTimeline
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ShowTimeline(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowTimeline");

	Params::W_EndRoundMainScreen_C_ShowTimeline Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowDetails
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ShowDetails(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowDetails");

	Params::W_EndRoundMainScreen_C_ShowDetails Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ShowVoting
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::ShowVoting(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ShowVoting");

	Params::W_EndRoundMainScreen_C_ShowVoting Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.MakeButtonActive
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_EndRoundMainScreen_C::MakeButtonActive(class UUserWidget* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "MakeButtonActive");

	Params::W_EndRoundMainScreen_C_MakeButtonActive Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_EndRoundMainScreen.W_EndRoundMainScreen_C.ScreenChangeFinished
// (Public, BlueprintCallable, BlueprintEvent)

void UW_EndRoundMainScreen_C::ScreenChangeFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_EndRoundMainScreen_C", "ScreenChangeFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

