#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ServerInfo

#include "Basic.hpp"

#include "W_ServerInfo_classes.hpp"
#include "W_ServerInfo_parameters.hpp"


namespace SDK
{

// Function W_ServerInfo.W_ServerInfo_C.ExecuteUbergraph_W_ServerInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerInfo_C::ExecuteUbergraph_W_ServerInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerInfo_C", "ExecuteUbergraph_W_ServerInfo");

	Params::W_ServerInfo_C_ExecuteUbergraph_W_ServerInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerInfo.W_ServerInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ServerInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ServerInfo.W_ServerInfo_C.UpdateData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_ServerInfo_C::UpdateData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerInfo_C", "UpdateData");

	UObject::ProcessEvent(Func, nullptr);
}

}

