#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SquadIndexMarker

#include "Basic.hpp"

#include "W_SquadIndexMarker_classes.hpp"
#include "W_SquadIndexMarker_parameters.hpp"


namespace SDK
{

// Function W_SquadIndexMarker.W_SquadIndexMarker_C.Update
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewSquadText                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_SquadIndexMarker_C::Update(const class FText& NewSquadText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SquadIndexMarker_C", "Update");

	Params::W_SquadIndexMarker_C_Update Parms{};

	Parms.NewSquadText = std::move(NewSquadText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SquadIndexMarker.W_SquadIndexMarker_C.GetWidth
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Width                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SquadIndexMarker_C::GetWidth(float* Width)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SquadIndexMarker_C", "GetWidth");

	Params::W_SquadIndexMarker_C_GetWidth Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Width != nullptr)
		*Width = Parms.Width;
}

}

