#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TicketDetailsCategory_Vehicles

#include "Basic.hpp"

#include "W_TicketDetailsCategory_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_TicketDetailsCategory_Vehicles.W_TicketDetailsCategory_Vehicles_C
// 0x0000 (0x0380 - 0x0380)
class UW_TicketDetailsCategory_Vehicles_C final : public UW_TicketDetailsCategory_C
{
public:
	void AddRow(const struct FSQTicketsSummaryVehicleRecord& Record);
	void FillEmptyRecords(class UUMG_Tooltip_C* Tooltip);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_TicketDetailsCategory_Vehicles_C">();
	}
	static class UW_TicketDetailsCategory_Vehicles_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TicketDetailsCategory_Vehicles_C>();
	}
};
static_assert(alignof(UW_TicketDetailsCategory_Vehicles_C) == 0x000008, "Wrong alignment on UW_TicketDetailsCategory_Vehicles_C");
static_assert(sizeof(UW_TicketDetailsCategory_Vehicles_C) == 0x000380, "Wrong size on UW_TicketDetailsCategory_Vehicles_C");

}

