#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TicketDetailsCategory

#include "Basic.hpp"

#include "W_TicketDetailsCategory_classes.hpp"
#include "W_TicketDetailsCategory_parameters.hpp"


namespace SDK
{

// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.ExecuteUbergraph_W_TicketDetailsCategory
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::ExecuteUbergraph_W_TicketDetailsCategory(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "ExecuteUbergraph_W_TicketDetailsCategory");

	Params::W_TicketDetailsCategory_C_ExecuteUbergraph_W_TicketDetailsCategory Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_TicketDetailsCategory_C::BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_TicketDetailsCategory_C::BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_TicketDetailsCategory_C::BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "BndEvt__W_TicketDetailsCategory_MainButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_TicketDetailsCategory_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_TicketDetailsCategory_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "PreConstruct");

	Params::W_TicketDetailsCategory_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.SetScore
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Absolute                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_TicketDetailsCategory_C::SetScore(int32 Score, bool Absolute)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "SetScore");

	Params::W_TicketDetailsCategory_C_SetScore Parms{};

	Parms.Score = Score;
	Parms.Absolute = Absolute;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.UpdateStatus
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_TicketDetailsCategory_C::UpdateStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "UpdateStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.ToggleRecordsVisib
// (Public, BlueprintCallable, BlueprintEvent)

void UW_TicketDetailsCategory_C::ToggleRecordsVisib()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "ToggleRecordsVisib");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.FillEmptyRecords
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUMG_Tooltip_C*                   Tooltip                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::FillEmptyRecords(class UUMG_Tooltip_C* Tooltip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "FillEmptyRecords");

	Params::W_TicketDetailsCategory_C_FillEmptyRecords Parms{};

	Parms.Tooltip = Tooltip;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.TryAddRecord
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSQTicketsSummaryRecord          Record                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// bool                                    Added                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_TicketDetailsCategory_C::TryAddRecord(struct FSQTicketsSummaryRecord& Record, bool* Added)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "TryAddRecord");

	Params::W_TicketDetailsCategory_C_TryAddRecord Parms{};

	Parms.Record = std::move(Record);

	UObject::ProcessEvent(Func, &Parms);

	Record = std::move(Parms.Record);

	if (Added != nullptr)
		*Added = Parms.Added;
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.GetMaxValues
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Units                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   UnitTickets                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Score                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::GetMaxValues(int32* Units, int32* UnitTickets, int32* Score)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "GetMaxValues");

	Params::W_TicketDetailsCategory_C_GetMaxValues Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Units != nullptr)
		*Units = Parms.Units;

	if (UnitTickets != nullptr)
		*UnitTickets = Parms.UnitTickets;

	if (Score != nullptr)
		*Score = Parms.Score;
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.UpdateProgressBar
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaxScore                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::UpdateProgressBar(int32& MaxScore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "UpdateProgressBar");

	Params::W_TicketDetailsCategory_C_UpdateProgressBar Parms{};

	Parms.MaxScore = MaxScore;

	UObject::ProcessEvent(Func, &Parms);

	MaxScore = Parms.MaxScore;
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.AddWidgetToSubcategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      NewWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::AddWidgetToSubcategory(class UUserWidget* NewWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "AddWidgetToSubcategory");

	Params::W_TicketDetailsCategory_C_AddWidgetToSubcategory Parms{};

	Parms.NewWidget = NewWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.UpdateMainScore
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Score                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_C::UpdateMainScore(int32* Score)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "UpdateMainScore");

	Params::W_TicketDetailsCategory_C_UpdateMainScore Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Score != nullptr)
		*Score = Parms.Score;
}


// Function W_TicketDetailsCategory.W_TicketDetailsCategory_C.ChangeContentVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewVisibile                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    WithChildren                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_TicketDetailsCategory_C::ChangeContentVisibility(bool NewVisibile, bool WithChildren)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_C", "ChangeContentVisibility");

	Params::W_TicketDetailsCategory_C_ChangeContentVisibility Parms{};

	Parms.NewVisibile = NewVisibile;
	Parms.WithChildren = WithChildren;

	UObject::ProcessEvent(Func, &Parms);
}

}

