#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TicketDetailsCategory_Logistics

#include "Basic.hpp"

#include "W_TicketDetailsCategory_Logistics_classes.hpp"
#include "W_TicketDetailsCategory_Logistics_parameters.hpp"


namespace SDK
{

// Function W_TicketDetailsCategory_Logistics.W_TicketDetailsCategory_Logistics_C.AddRow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSQTicketsSummaryRecord          Fob                                                    (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// int32                                   Ammo                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Construction                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_Logistics_C::AddRow(struct FSQTicketsSummaryRecord& Fob, int32& Ammo, int32& Construction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_Logistics_C", "AddRow");

	Params::W_TicketDetailsCategory_Logistics_C_AddRow Parms{};

	Parms.Fob = std::move(Fob);
	Parms.Ammo = Ammo;
	Parms.Construction = Construction;

	UObject::ProcessEvent(Func, &Parms);

	Fob = std::move(Parms.Fob);
	Ammo = Parms.Ammo;
	Construction = Parms.Construction;
}


// Function W_TicketDetailsCategory_Logistics.W_TicketDetailsCategory_Logistics_C.GetMaxValues
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Units                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   UnitTickets                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Score                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_Logistics_C::GetMaxValues(int32* Units, int32* UnitTickets, int32* Score)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_Logistics_C", "GetMaxValues");

	Params::W_TicketDetailsCategory_Logistics_C_GetMaxValues Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Units != nullptr)
		*Units = Parms.Units;

	if (UnitTickets != nullptr)
		*UnitTickets = Parms.UnitTickets;

	if (Score != nullptr)
		*Score = Parms.Score;
}


// Function W_TicketDetailsCategory_Logistics.W_TicketDetailsCategory_Logistics_C.UpdateProgressBar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaxScore                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_Logistics_C::UpdateProgressBar(int32& MaxScore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_Logistics_C", "UpdateProgressBar");

	Params::W_TicketDetailsCategory_Logistics_C_UpdateProgressBar Parms{};

	Parms.MaxScore = MaxScore;

	UObject::ProcessEvent(Func, &Parms);

	MaxScore = Parms.MaxScore;
}


// Function W_TicketDetailsCategory_Logistics.W_TicketDetailsCategory_Logistics_C.FillEmptyRecords
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUMG_Tooltip_C*                   Tooltip                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_TicketDetailsCategory_Logistics_C::FillEmptyRecords(class UUMG_Tooltip_C* Tooltip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_TicketDetailsCategory_Logistics_C", "FillEmptyRecords");

	Params::W_TicketDetailsCategory_Logistics_C_FillEmptyRecords Parms{};

	Parms.Tooltip = Tooltip;

	UObject::ProcessEvent(Func, &Parms);
}

}

