#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Tooltip_VehicleSeatItem

#include "Basic.hpp"

#include "W_Tooltip_VehicleSeatItem_classes.hpp"
#include "W_Tooltip_VehicleSeatItem_parameters.hpp"


namespace SDK
{

// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.ExecuteUbergraph_W_Tooltip_VehicleSeatItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Tooltip_VehicleSeatItem_C::ExecuteUbergraph_W_Tooltip_VehicleSeatItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "ExecuteUbergraph_W_Tooltip_VehicleSeatItem");

	Params::W_Tooltip_VehicleSeatItem_C_ExecuteUbergraph_W_Tooltip_VehicleSeatItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.Update Occupant
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSQVehicleOccupantInfo           Occupant_Info_0                                        (BlueprintVisible, BlueprintReadOnly, Parm)
// class USQMapWidgetVehicle*              Vehicle_Widget_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Is_Self_Team_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   My_Seat_ID_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Seat_Index_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Tooltip_VehicleSeatItem_C::Update_Occupant(const struct FSQVehicleOccupantInfo& Occupant_Info_0, class USQMapWidgetVehicle* Vehicle_Widget_0, bool Is_Self_Team_0, int32 My_Seat_ID_0, int32 Seat_Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "Update Occupant");

	Params::W_Tooltip_VehicleSeatItem_C_Update_Occupant Parms{};

	Parms.Occupant_Info_0 = std::move(Occupant_Info_0);
	Parms.Vehicle_Widget_0 = Vehicle_Widget_0;
	Parms.Is_Self_Team_0 = Is_Self_Team_0;
	Parms.My_Seat_ID_0 = My_Seat_ID_0;
	Parms.Seat_Index_0 = Seat_Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.Get Tint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     Out_Color                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Tooltip_VehicleSeatItem_C::Get_Tint(struct FLinearColor* Out_Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "Get Tint");

	Params::W_Tooltip_VehicleSeatItem_C_Get_Tint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out_Color != nullptr)
		*Out_Color = std::move(Parms.Out_Color);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.UpdateKitVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::UpdateKitVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "UpdateKitVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.UpdateSquadVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::UpdateSquadVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "UpdateSquadVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.UpdateRank
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::UpdateRank()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "UpdateRank");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.Update Fireteam
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::Update_Fireteam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "Update Fireteam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.Self Squad
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UW_Tooltip_VehicleSeatItem_C::Self_Squad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "Self Squad");

	Params::W_Tooltip_VehicleSeatItem_C_Self_Squad Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Tooltip_VehicleSeatItem.W_Tooltip_VehicleSeatItem_C.ShowHideCommanderStar
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Tooltip_VehicleSeatItem_C::ShowHideCommanderStar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Tooltip_VehicleSeatItem_C", "ShowHideCommanderStar");

	UObject::ProcessEvent(Func, nullptr);
}

}

