#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_VehicleSeatInfo

#include "Basic.hpp"

#include "W_VehicleSeatInfo_classes.hpp"
#include "W_VehicleSeatInfo_parameters.hpp"


namespace SDK
{

// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.ExecuteUbergraph_W_VehicleSeatInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_VehicleSeatInfo_C::ExecuteUbergraph_W_VehicleSeatInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "ExecuteUbergraph_W_VehicleSeatInfo");

	Params::W_VehicleSeatInfo_C_ExecuteUbergraph_W_VehicleSeatInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Update Occupant
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Seat_Index_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ASQPlayerState*                   Player_State_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Driver_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_VehicleSeatInfo_C::Update_Occupant(int32 Seat_Index_0, class ASQPlayerState* Player_State_0, bool Driver_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Update Occupant");

	Params::W_VehicleSeatInfo_C_Update_Occupant Parms{};

	Parms.Seat_Index_0 = Seat_Index_0;
	Parms.Player_State_0 = Player_State_0;
	Parms.Driver_0 = Driver_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_VehicleSeatInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Get Tint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     Out_Color                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_VehicleSeatInfo_C::Get_Tint(struct FLinearColor* Out_Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Get Tint");

	Params::W_VehicleSeatInfo_C_Get_Tint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out_Color != nullptr)
		*Out_Color = std::move(Parms.Out_Color);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.UpdateKitVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::UpdateKitVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "UpdateKitVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.UpdateSquadVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::UpdateSquadVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "UpdateSquadVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.UpdateRank
// (Public, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::UpdateRank()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "UpdateRank");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Update Fireteam
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::Update_Fireteam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Update Fireteam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Self Squad
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UW_VehicleSeatInfo_C::Self_Squad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Self Squad");

	Params::W_VehicleSeatInfo_C_Self_Squad Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Set Self Team
// (Public, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::Set_Self_Team()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Set Self Team");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.Set Squad ID
// (Public, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::Set_Squad_ID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "Set Squad ID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_VehicleSeatInfo.W_VehicleSeatInfo_C.ShowHideCommanderStar
// (Public, BlueprintCallable, BlueprintEvent)

void UW_VehicleSeatInfo_C::ShowHideCommanderStar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_VehicleSeatInfo_C", "ShowHideCommanderStar");

	UObject::ProcessEvent(Func, nullptr);
}

}

